<script lang="ts">
  import type { Evidence, Finding } from '../types';
  let { evidence, findings }: { evidence: Evidence[]; findings: Finding[] } = $props();
  let selectedId = $state('');
  let typeFilter = $state('');
  let filtered = $derived(evidence.filter((item) => !typeFilter || item.evidence_type === typeFilter));
  let selected = $derived(evidence.find((item) => item.id === selectedId) ?? filtered[0]);
  function findingLabel(id: string | null) { return findings.find((item) => item.id === id)?.display_id ?? null; }
</script>
<section class="workspace-page lifecycle-page" aria-labelledby="evidence-title"><header class="workspace-header"><div><span class="eyebrow">IMMUTABLE SNAPSHOTS</span><h1 id="evidence-title">Evidence</h1><p>Redacted point-in-time records remain intact if their source changes or is removed.</p></div><label class="compact-filter"><span>Type</span><select bind:value={typeFilter}><option value="">All types</option><option>HTTP Request/Response</option><option>Replay</option><option>Response Comparison</option><option>Operator Note</option><option>Text Excerpt</option></select></label></header><div class="lifecycle-split"><aside class="record-list">{#each filtered as item}<button class:active={selected?.id === item.id} type="button" onclick={() => (selectedId = item.id)}><span class="record-id">{item.display_id}</span><strong>{item.title}</strong><small>{item.evidence_type}</small><em>{findingLabel(item.finding_id) ?? 'Unlinked'}</em></button>{:else}<div class="empty-workspace"><span class="empty-glyph">▣</span><strong>No evidence</strong><p>Save a request, comparison, or operator note as evidence.</p></div>{/each}</aside>{#if selected}<article class="report-detail"><header class="report-heading"><div><span class="eyebrow">{selected.display_id} · {selected.evidence_type}</span><h2>{selected.title}</h2><code>{findingLabel(selected.finding_id) ?? 'Not linked to a finding'}</code></div><span class="immutable-badge">IMMUTABLE</span></header><div class="context-grid"><span><small>CAPTURED</small><strong>{new Date(selected.captured_at).toLocaleString()}</strong></span><span><small>AUTHOR</small><strong>{selected.author_label}</strong></span><span><small>SOURCE</small><strong>{selected.source_exchange_id?.slice(0, 8) ?? selected.source_comparison_id?.slice(0, 8) ?? 'Operator'}</strong></span></div><section class="report-section"><h3>Captured snapshot</h3><pre class="evidence-snapshot">{JSON.stringify(selected.snapshot, null, 2)}</pre></section>{#if selected.notes.length}<section class="report-section"><h3>Notes</h3>{#each selected.notes as note}<div class="timeline-item"><strong>{note.author_label}</strong><time>{new Date(note.created_at).toLocaleString()}</time><p>{note.body}</p></div>{/each}</section>{/if}</article>{:else}<div class="detail-placeholder">Select evidence to inspect its snapshot.</div>{/if}</div></section>
